# NOTA: "Additional contexts" era presente nel file .yaml
#        originario, tuttavia è stato deprecato e crashava.

#        Guardando il codice di alcuni compagni ho anche notato
#        che il file .env a volte aveva le variabili d'ambiente
#        impostate male.

#        Infine, non utilizzare il comando ```sudo chmod 777 -R .```
#        al sulla cartella di questo file, causa problemi durante
#        avvio e chiusura del container.

version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: dev/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_dev
    volumes:
      - ${USER_BASE_FOLDER}:/home/app
    networks:
      - its_network
    restart: unless-stopped
    depends_on:
      - postgresql

  postgresql:
    build:
      context: postgresql
    container_name: ${COMPOSE_PROJECT_NAME}_postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRESQL_EXPOSED_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - its_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${COMPOSE_PROJECT_NAME}_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
    networks:
      - its_network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  its_network:
    driver: bridge